CREATE TABLE LOCATIONS( 
LOCATION_ID int PRIMARY KEY NOT NULL, 
STREET_ADDRESS VARCHAR(40),
POSTAL_CODE    VARCHAR(12),
CITY VARCHAR(30) NOT NULL, 
STATE_PROVINCE VARCHAR(25),
COUNTRY_ID  VARCHAR(2)
) ;